export const REGISTER_EMAIL_REQUEST = "REGISTER_EMAIL_REQUEST";
export const REGISTER_EMAIL_SUCCESS = "REGISTER_EMAIL_SUCCESS";
export const REGISTER_EMAIL_FAILURE = "REGISTER_EMAIL_FAILURE";

export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILURE = "VERIFY_EMAIL_FAILURE";

export const SET_PASSWORD_EMAIL_REQUEST = "SET_PASSWORD_EMAIL_REQUEST";
export const SET_PASSWORD_EMAIL_SUCCESS = "SET_PASSWORD_EMAIL_SUCCESS";
export const SET_PASSWORD_EMAIL_FAILURE = "SET_PASSWORD_EMAIL_FAILURE";

export const LOGIN_EMAIL_REQUEST = "LOGIN_EMAIL_REQUEST";
export const LOGIN_EMAIL_SUCCESS = "LOGIN_EMAIL_SUCCESS";
export const LOGIN_EMAIL_FAILURE = "LOGIN_EMAIL_FAILURE";

export const LOG_OUT_EMAIL_REQUEST = "LOG_OUT_EMAIL_REQUEST";
export const LOG_OUT_EMAIL_SUCCESS = "LOG_OUT_EMAIL_SUCCESS";
export const LOG_OUT_EMAIL_FAILURE = "LOG_OUT_EMAIL_FAILURE";